# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-11 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 15, 21, 38, 396558, tzinfo=utc)),
        ),
    ]
