# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-11 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171111_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 16, 51, 28, 274967, tzinfo=utc)),
        ),
    ]
